# .github/workflows/cmake.yml
name: Build Minecraft Hack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - uses: actions/checkout@v4
    
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
      
    - name: Build
      working-directory: ./build
      run: make
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libminecraft_hack.so
        path: build/libminecraft_hack.so
